name: pygame wasm github deployment

on:
  push:
    branches: ["main"]

permissions:
  context: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [-f requirements.txt ]; then pip install -r requirements.txt fi
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest
      - name: Pygbag build
        run: |
          pygbag --build .
      - name: Upload Github pages artifact
<<<<<<< HEAD
        uses: actions/upload-pages-artifact@v1.0.8
=======
        users: actions/upload-pages-artifact@v1.0.8
>>>>>>> develop
        with:
          name: github-pages
          path: ./build/web/.
          retention-days: 5
